-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.patient
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    age integer,
    contact integer,
    gender character varying(255) COLLATE pg_catalog."default",
    healthcareprovider character varying(255) COLLATE pg_catalog."default",
    healthinsuranceno character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    occupation character varying(255) COLLATE pg_catalog."default",
    patientaddress character varying(255) COLLATE pg_catalog."default",
    patient_doctor_id integer,
    CONSTRAINT patient_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.doctor
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    about character varying(255) COLLATE pg_catalog."default",
    doctor_address character varying(255) COLLATE pg_catalog."default",
    doctorname character varying(255) COLLATE pg_catalog."default",
    hospital_name character varying(255) COLLATE pg_catalog."default",
    profile_picture character varying(255) COLLATE pg_catalog."default",
    speciality character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT doctor_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.report
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    bloodpressure character varying(255) COLLATE pg_catalog."default",
    createddate date,
    patienthistory character varying(255) COLLATE pg_catalog."default",
    pulserate double precision,
    weight double precision,
    report_doctor_id integer,
    report_followupdoctor_id integer,
    report_patient_id integer,
    CONSTRAINT report_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.diet
(
    dietid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    report_diet_id integer,
    CONSTRAINT diet_pkey PRIMARY KEY (dietid)
    );

CREATE TABLE IF NOT EXISTS public.medicin
(
    medicinid integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    dosage character varying(255) COLLATE pg_catalog."default",
    drugname character varying(255) COLLATE pg_catalog."default",
    unit character varying(255) COLLATE pg_catalog."default",
    report_medicin_id integer,
    CONSTRAINT medicin_pkey PRIMARY KEY (medicinid)
    );

CREATE TABLE IF NOT EXISTS public.report_allergies
(
    report_id integer NOT NULL,
    allergies character varying(255) COLLATE pg_catalog."default"
    );

CREATE TABLE IF NOT EXISTS public.report_disabilities
(
    report_id integer NOT NULL,
    disabilities character varying(255) COLLATE pg_catalog."default"
    );

CREATE TABLE IF NOT EXISTS public.invoice
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    quantity integer,
    salesprice integer,
    patient_invoice_id integer,
    CONSTRAINT invoice_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.item
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    itemname character varying(255) COLLATE pg_catalog."default",
    itemno integer,
    samname character varying(255) COLLATE pg_catalog."default",
    testsortname character varying(255) COLLATE pg_catalog."default",
    unitprice integer,
    invoice_id integer,
    CONSTRAINT item_pkey PRIMARY KEY (id)
    );

ALTER TABLE IF EXISTS public.patient
    ADD CONSTRAINT fkd6dnl8i2rvs7cye1r5tojlrma FOREIGN KEY (patient_doctor_id)
    REFERENCES public.doctor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS uk48hdo2x14t9kn96a5mtkqeh1e
    ON public.patient(patient_doctor_id);


ALTER TABLE IF EXISTS public.report
    ADD CONSTRAINT fk52x1gnfdaeobnmcl1nownl76b FOREIGN KEY (report_patient_id)
    REFERENCES public.patient (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukoyd845pune4p8wdaej8na3062
    ON public.report(report_patient_id);


ALTER TABLE IF EXISTS public.report
    ADD CONSTRAINT fkesqu1bh1hyrjuwa6e465a9lkv FOREIGN KEY (report_followupdoctor_id)
    REFERENCES public.doctor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukjian8g5uigh9fgjl7cu4kyihf
    ON public.report(report_followupdoctor_id);


ALTER TABLE IF EXISTS public.report
    ADD CONSTRAINT fkfpnfwrj2qwmnlroswrj1iq1y9 FOREIGN KEY (report_doctor_id)
    REFERENCES public.doctor (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukhmciud4a2hrobsuo8bg1abu3m
    ON public.report(report_doctor_id);


ALTER TABLE IF EXISTS public.diet
    ADD CONSTRAINT fk9ppmj1dnng6brp4s9y4w72jmy FOREIGN KEY (report_diet_id)
    REFERENCES public.report (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.medicin
    ADD CONSTRAINT fk996r8e10381xopsvda4lbrae0 FOREIGN KEY (report_medicin_id)
    REFERENCES public.report (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.report_allergies
    ADD CONSTRAINT fknn46e8i61kgsaxf3qcrhw0en4 FOREIGN KEY (report_id)
    REFERENCES public.report (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.report_disabilities
    ADD CONSTRAINT fkiquyc8kpxts0b7o0265b0v7i9 FOREIGN KEY (report_id)
    REFERENCES public.report (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.invoice
    ADD CONSTRAINT fknuwi5b709095qumhhahpiee3w FOREIGN KEY (patient_invoice_id)
    REFERENCES public.patient (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ukntlvupai56fwwr9foyapunad1
    ON public.invoice(patient_invoice_id);


ALTER TABLE IF EXISTS public.item
    ADD CONSTRAINT fkfk1ol4trn6i72renhjm2x79mo FOREIGN KEY (invoice_id)
    REFERENCES public.invoice (id) MATCH SIMPLE
    ON UPDATE NO ACTION
       ON DELETE NO ACTION;

END;